{-# LANGUAGE DeriveDataTypeable #-}
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE OverloadedStrings #-}
{-# OPTIONS_GHC -fno-warn-missing-fields #-}
{-# OPTIONS_GHC -fno-warn-missing-signatures #-}
{-# OPTIONS_GHC -fno-warn-name-shadowing #-}
{-# OPTIONS_GHC -fno-warn-unused-imports #-}
{-# OPTIONS_GHC -fno-warn-unused-matches #-}

-----------------------------------------------------------------
-- Autogenerated by Thrift Compiler (0.11.0)                      --
--                                                             --
-- DO NOT EDIT UNLESS YOU ARE SURE YOU KNOW WHAT YOU ARE DOING --
-----------------------------------------------------------------

module BaggageRestrictionManager where
import Prelude (($), (.), (>>=), (==), (++))
import qualified Prelude as P
import qualified Control.Exception as X
import qualified Control.Monad as M ( liftM, ap, when )
import Data.Functor ( (<$>) )
import qualified Data.ByteString.Lazy as LBS
import qualified Data.Hashable as H
import qualified Data.Int as I
import qualified Data.Maybe as M (catMaybes)
import qualified Data.Text.Lazy.Encoding as E ( decodeUtf8, encodeUtf8 )
import qualified Data.Text.Lazy as LT
import qualified GHC.Generics as G (Generic)
import qualified Data.Typeable as TY ( Typeable )
import qualified Data.HashMap.Strict as Map
import qualified Data.HashSet as Set
import qualified Data.Vector as Vector
import qualified Test.QuickCheck.Arbitrary as QC ( Arbitrary(..) )
import qualified Test.QuickCheck as QC ( elements )

import qualified Thrift as T
import qualified Thrift.Types as T
import qualified Thrift.Arbitraries as T


import Baggage_Types
import qualified BaggageRestrictionManager_Iface as Iface
-- HELPER FUNCTIONS AND STRUCTURES --

data GetBaggageRestrictions_args = GetBaggageRestrictions_args  { getBaggageRestrictions_args_serviceName :: LT.Text
  } deriving (P.Show,P.Eq,G.Generic,TY.Typeable)
instance H.Hashable GetBaggageRestrictions_args where
  hashWithSalt salt record = salt   `H.hashWithSalt` getBaggageRestrictions_args_serviceName record  
instance QC.Arbitrary GetBaggageRestrictions_args where 
  arbitrary = M.liftM GetBaggageRestrictions_args (QC.arbitrary)
  shrink obj | obj == default_GetBaggageRestrictions_args = []
             | P.otherwise = M.catMaybes
    [ if obj == default_GetBaggageRestrictions_args{getBaggageRestrictions_args_serviceName = getBaggageRestrictions_args_serviceName obj} then P.Nothing else P.Just $ default_GetBaggageRestrictions_args{getBaggageRestrictions_args_serviceName = getBaggageRestrictions_args_serviceName obj}
    ]
from_GetBaggageRestrictions_args :: GetBaggageRestrictions_args -> T.ThriftVal
from_GetBaggageRestrictions_args record = T.TStruct $ Map.fromList $ M.catMaybes
  [ (\_v9 -> P.Just (1, ("serviceName",T.TString $ E.encodeUtf8 _v9))) $ getBaggageRestrictions_args_serviceName record
  ]
write_GetBaggageRestrictions_args :: T.Protocol p => p -> GetBaggageRestrictions_args -> P.IO ()
write_GetBaggageRestrictions_args oprot record = T.writeVal oprot $ from_GetBaggageRestrictions_args record
encode_GetBaggageRestrictions_args :: T.StatelessProtocol p => p -> GetBaggageRestrictions_args -> LBS.ByteString
encode_GetBaggageRestrictions_args oprot record = T.serializeVal oprot $ from_GetBaggageRestrictions_args record
to_GetBaggageRestrictions_args :: T.ThriftVal -> GetBaggageRestrictions_args
to_GetBaggageRestrictions_args (T.TStruct fields) = GetBaggageRestrictions_args{
  getBaggageRestrictions_args_serviceName = P.maybe (getBaggageRestrictions_args_serviceName default_GetBaggageRestrictions_args) (\(_,_val11) -> (case _val11 of {T.TString _val12 -> E.decodeUtf8 _val12; _ -> P.error "wrong type"})) (Map.lookup (1) fields)
  }
to_GetBaggageRestrictions_args _ = P.error "not a struct"
read_GetBaggageRestrictions_args :: T.Protocol p => p -> P.IO GetBaggageRestrictions_args
read_GetBaggageRestrictions_args iprot = to_GetBaggageRestrictions_args <$> T.readVal iprot (T.T_STRUCT typemap_GetBaggageRestrictions_args)
decode_GetBaggageRestrictions_args :: T.StatelessProtocol p => p -> LBS.ByteString -> GetBaggageRestrictions_args
decode_GetBaggageRestrictions_args iprot bs = to_GetBaggageRestrictions_args $ T.deserializeVal iprot (T.T_STRUCT typemap_GetBaggageRestrictions_args) bs
typemap_GetBaggageRestrictions_args :: T.TypeMap
typemap_GetBaggageRestrictions_args = Map.fromList [(1,("serviceName",T.T_STRING))]
default_GetBaggageRestrictions_args :: GetBaggageRestrictions_args
default_GetBaggageRestrictions_args = GetBaggageRestrictions_args{
  getBaggageRestrictions_args_serviceName = ""}
data GetBaggageRestrictions_result = GetBaggageRestrictions_result  { getBaggageRestrictions_result_success :: (Vector.Vector BaggageRestriction)
  } deriving (P.Show,P.Eq,G.Generic,TY.Typeable)
instance H.Hashable GetBaggageRestrictions_result where
  hashWithSalt salt record = salt   `H.hashWithSalt` getBaggageRestrictions_result_success record  
instance QC.Arbitrary GetBaggageRestrictions_result where 
  arbitrary = M.liftM GetBaggageRestrictions_result (QC.arbitrary)
  shrink obj | obj == default_GetBaggageRestrictions_result = []
             | P.otherwise = M.catMaybes
    [ if obj == default_GetBaggageRestrictions_result{getBaggageRestrictions_result_success = getBaggageRestrictions_result_success obj} then P.Nothing else P.Just $ default_GetBaggageRestrictions_result{getBaggageRestrictions_result_success = getBaggageRestrictions_result_success obj}
    ]
from_GetBaggageRestrictions_result :: GetBaggageRestrictions_result -> T.ThriftVal
from_GetBaggageRestrictions_result record = T.TStruct $ Map.fromList $ M.catMaybes
  [ (\_v15 -> P.Just (0, ("success",T.TList (T.T_STRUCT typemap_BaggageRestriction) $ P.map (\_v17 -> from_BaggageRestriction _v17) $ Vector.toList _v15))) $ getBaggageRestrictions_result_success record
  ]
write_GetBaggageRestrictions_result :: T.Protocol p => p -> GetBaggageRestrictions_result -> P.IO ()
write_GetBaggageRestrictions_result oprot record = T.writeVal oprot $ from_GetBaggageRestrictions_result record
encode_GetBaggageRestrictions_result :: T.StatelessProtocol p => p -> GetBaggageRestrictions_result -> LBS.ByteString
encode_GetBaggageRestrictions_result oprot record = T.serializeVal oprot $ from_GetBaggageRestrictions_result record
to_GetBaggageRestrictions_result :: T.ThriftVal -> GetBaggageRestrictions_result
to_GetBaggageRestrictions_result (T.TStruct fields) = GetBaggageRestrictions_result{
  getBaggageRestrictions_result_success = P.maybe (getBaggageRestrictions_result_success default_GetBaggageRestrictions_result) (\(_,_val19) -> (case _val19 of {T.TList _ _val20 -> (Vector.fromList $ P.map (\_v21 -> (case _v21 of {T.TStruct _val22 -> (to_BaggageRestriction (T.TStruct _val22)); _ -> P.error "wrong type"})) _val20); _ -> P.error "wrong type"})) (Map.lookup (0) fields)
  }
to_GetBaggageRestrictions_result _ = P.error "not a struct"
read_GetBaggageRestrictions_result :: T.Protocol p => p -> P.IO GetBaggageRestrictions_result
read_GetBaggageRestrictions_result iprot = to_GetBaggageRestrictions_result <$> T.readVal iprot (T.T_STRUCT typemap_GetBaggageRestrictions_result)
decode_GetBaggageRestrictions_result :: T.StatelessProtocol p => p -> LBS.ByteString -> GetBaggageRestrictions_result
decode_GetBaggageRestrictions_result iprot bs = to_GetBaggageRestrictions_result $ T.deserializeVal iprot (T.T_STRUCT typemap_GetBaggageRestrictions_result) bs
typemap_GetBaggageRestrictions_result :: T.TypeMap
typemap_GetBaggageRestrictions_result = Map.fromList [(0,("success",(T.T_LIST (T.T_STRUCT typemap_BaggageRestriction))))]
default_GetBaggageRestrictions_result :: GetBaggageRestrictions_result
default_GetBaggageRestrictions_result = GetBaggageRestrictions_result{
  getBaggageRestrictions_result_success = Vector.empty}
process_getBaggageRestrictions (seqid, iprot, oprot, handler) = do
  args <- read_GetBaggageRestrictions_args iprot
  (X.catch
    (do
      val <- Iface.getBaggageRestrictions handler (getBaggageRestrictions_args_serviceName args)
      let res = default_GetBaggageRestrictions_result{getBaggageRestrictions_result_success = val}
      T.writeMessage oprot ("getBaggageRestrictions", T.M_REPLY, seqid) $
        write_GetBaggageRestrictions_result oprot res)
    ((\_ -> do
      T.writeMessage oprot ("getBaggageRestrictions", T.M_EXCEPTION, seqid) $
        T.writeAppExn oprot (T.AppExn T.AE_UNKNOWN "")) :: X.SomeException -> P.IO ()))
proc_ handler (iprot,oprot) (name,typ,seqid) = case name of
  "getBaggageRestrictions" -> process_getBaggageRestrictions (seqid,iprot,oprot,handler)
  _ -> do
    _ <- T.readVal iprot (T.T_STRUCT Map.empty)
    T.writeMessage oprot (name,T.M_EXCEPTION,seqid) $
      T.writeAppExn oprot (T.AppExn T.AE_UNKNOWN_METHOD ("Unknown function " ++ LT.unpack name))
process handler (iprot, oprot) = do
  T.readMessage iprot (
    proc_ handler (iprot,oprot))
  P.return P.True
